import Header from '@/Components/Header'
import { Inter } from 'next/font/google';
import './globals.css'
import HomeInstaSec from '@/Components/HomeInstaSec';
import Footer from '@/Components/Footer';

const inter = Inter({ subsets: ['latin'] });


export const metadata = {
  title: 'Sand & Stone App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <body className={inter.className}>
        <Header/>
        {children}
       <HomeInstaSec/>
       <Footer/>

        
        </body>
    </html>
  )
}
